### ISSUE TITLE
things to keep on the homepage

### ISSUE THREAD

**Issue by kat** [AOGPN/opengovernment.org.au#15] opened 2016-01-19 06:03 UTC
```
Remove the logo (not needed at this time)
Rewrite the section 'UK Open Gov'
```

 (via Craig) - Homepage -    

Keep latest posts (discussed in Updates section)
    Keep Orange section (Transparency, Participation, Accountability) - recolour to pallette.
    Keep latest updates (discussed in Updates section)
    Keep Tweets (display #OGPau, #OGP & @opengovpart until we have a network twitter account in place) - note this has a small risk should people publish inappropriate material using either of the hashtags. If this isn't considered acceptable we can deactivate this section temporarily.
    Keep events section (Coming up and Recent) - populate currently based on Gov Info Sessions & Regional/Global OGP schedule plus add our scheduled meetings as we go.

**Comment by equivalentideas** [comment] 2016-01-19 06:27
This issue feels like it's handling too much stuff. I think we should try to just have issues for things that need changing, and assume that everything else will stay the same. As I understand this initial work is to just transfer it as is and translate.

> Rewrite the section 'UK Open Gov'

Is a duplicate of #16 so we can leave that.

The other issues are all keeping things aside from an adjustment to the twitter feed. I'll make a new issue for that and then I think we can close this issue.

**Comment by kat** [comment] 2016-01-19 08:54
cool, makes sense. thanks @equivalentideas

**Comment by equivalentideas** [comment] 2016-01-22 01:17
I've broken out the Twitter feed issue in #31 , so I'll close this now.

**Closed as completed by equivalentideas** 2016-01-22 01:17 UTC
Labels: theme
