### ISSUE TITLE
Slogan sitting below the logo instead of off to the right in Firefox

### ISSUE THREAD

**Issue by henare** [AOGPN/opengovernment.org.au#32] opened 2016-01-22 03:17 UTC
Compare our page to the UK's.

**Comment by equivalentideas** [comment] 2016-01-22 03:21
Are you referring to the site header?

Could you add a screenshot? I'm not sure what the issue is about. Here's what I see in the header on a wide screen:

![screen shot 2016-01-22 at 2 19 07 pm](https://cloud.githubusercontent.com/assets/1239550/12501603/218ae8be-c113-11e5-9751-03868100a9ca.png)
![screen shot 2016-01-22 at 2 19 03 pm](https://cloud.githubusercontent.com/assets/1239550/12501604/218f0e4e-c113-11e5-908a-dc560fa741b2.png)

**Comment by henare** [comment] 2016-01-22 03:28
Tested on Chrome and it's OK so it's just Firefox:

![selection_001](https://cloud.githubusercontent.com/assets/48945/12501725/68688510-c114-11e5-94f2-dceec9c4d098.png)

**Comment by equivalentideas** [comment] 2016-01-22 05:36
Fixed in 9eb8e60ee45902bc186ba12b73f37d77189b2a3f

**Closed as completed by equivalentideas** 2016-01-22 05:36 UTC
Labels: bug, theme
